### ISSUE TITLE
Trino 406 upgrade altered connectivity - unable to execute parameterized queries (FailedToObtainAddedPrepareHeader)

### ISSUE THREAD

**Issue by dnullify** [mvanderlee/aiotrino#2]
The organization I work for just updated to trino 406, which seems to have changed the way connections work. 

I am using aiotrino to make asynchronous queries, the queries are using qmark substitution and am getting the following error:

`Traceback (most recent call last):
  File "/Users/snag/code/oneoff/trino/main.py", line 218, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/snag/code/oneoff/trino/main.py", line 208, in main
    await cur.execute(query, params=params)
  File "/Users/snag/code/oneoff/venv/lib/python3.9/site-packages/aiotrino/dbapi.py", line 385, in execute
    added_prepare_header = await self._prepare_statement(
  File "/Users/snag/code/oneoff/venv/lib/python3.9/site-packages/aiotrino/dbapi.py", line 283, in _prepare_statement
    raise aiotrino.exceptions.FailedToObtainAddedPrepareHeader
aiotrino.exceptions.FailedToObtainAddedPrepareHeader
`

I am not sure how to debug this issue, but it looks like trino will return no response body under certain conditions from 406 onwards

**Comment by dnullify** [comment]
It looks like cursor._prepare_statement executes - but I am no longer getting an api response with headers. 

I added the following print statements:
```        print(f"query id: {query.query_id}")
        print(f"stats: {query._stats}")
```

result:
```query id: 20230718_191655_07572_grym9
stats: {'queryId': '20230718_191655_07572_grym9', 'state': 'QUEUED', 'queued': True, 'scheduled': False, 'nodes': 0, 'totalSplits': 0, 'queuedSplits': 0, 'runningSplits': 0, 'completedSplits': 0, 'cpuTimeMillis': 0, 'wallTimeMillis': 0, 'queuedTimeMillis': 0, 'elapsedTimeMillis': 0, 'processedRows': 0, 'processedBytes': 0, 'physicalInputBytes': 0, 'peakMemoryBytes': 0, 'spilledBytes': 0}
Traceback (most recent call last):
  File "/Users/d/code/oneoff/trino/main.py", line 61, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/d/code/oneoff/trino/main.py", line 48, in main
    await cur.execute(pquery, params=param)
  File "/Users/d/code/oneoff/trino/venv/lib/python3.9/site-packages/aiotrino/dbapi.py", line 387, in execute
    added_prepare_header = await self._prepare_statement(
  File "/Users/d/code/oneoff/trino/venv/lib/python3.9/site-packages/aiotrino/dbapi.py", line 285, in _prepare_statement
    raise aiotrino.exceptions.FailedToObtainAddedPrepareHeader
aiotrino.exceptions.FailedToObtainAddedPrepareHeader```

I reached out to the infrastructure team managing trino and was told:
"Trino 406 has changed to no response for ddl statement executed in trino python client"

**Comment by mvanderlee** [comment]
@dnullify The fix was released in version 0.2.2

**Comment by dnullify** [comment]
Thanks @mvanderlee ! I learned a lot digging through your code!
